
language: generic 

services:
  - docker

before_install:
  - docker build -t eikkon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eikkon/react-test npm test

after_success:
  - docker build -t eikkon/multi-client ./client
  - docker build -t eikkon/multi-nginx ./nginx
  - docker build -t eikkon/multi-server ./server
  - docker build -t eikkon/multi-worker ./worker
  #Log in to the docker CLI blabla blabla
  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push eikkon/multi-client 
  - docker push eikkon/multi-nginx 
  - docker push eikkon/multi-server 
  - docker push eikkon/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: 'eu-north-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-eu-north-1-953823691034'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
