language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t eikkon/react/test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eikkon/react-test npm test -- --coverage

after_success:
  - docker build -t eikkon/multi-client ./client
  - docker build -t eikkon/multi-nginx ./nginx
  - docker build -t eikkon/multi-server ./server
  - docker build -t eikkon/multi-worker ./worker